### PR TITLE
Interactive personalisation and quiz screen

### LINKED ISSUE #9: Personalisation test page

### LINKED ISSUE #12: Quiz page

### PR DESCRIPTION
**Pull request by florentianayuwono**
Buttons are pressable and navigable
image
image

### CODE REVIEW

**Comment by florentianayuwono** [comment]
image
Is this okay? @liviamil

**Comment by liviamil** [comment]
image

I would still think the gap could be smaller, and the use of font family could be Medium, Poppins. But this is good enough for now, we can just improve this if we still have time.

**Comment by florentianayuwono** [comment]
image
This one w500

**Review by liviamil — APPROVED** [review]
Looks good!

**Comment by florentianayuwono** [comment]
@liviamil I forgot to add new pr for this:
image
image

**Comment by florentianayuwono** [comment]
image
Is it like this the finish button?

**Comment by liviamil** [comment]
Yup looks like it! So it will be ‘selesai’ instead of ‘kirim’ right?

**Pull request merged**
